[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://ollhtyeflpggdazrsqsq.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_vXtlD6VqEY8u_tBSdmw-0A_hxEIlf2j"

[[plugins]]
  package = "@netlify/plugin-nextjs"
